name: Hello from AWS

on:
  push:
  
permissions:
  id-token: write

jobs:
  greeting:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::589918074230:role/aws-gh-oidc
    - name: Print AWS SSM Parameter
      run: aws ssm get-parameter --name=hello_aws-gh-oidc --query Parameter.Value
    - name: Print assumed role
      run: aws sts get-caller-identity
